from pptx.util import Pt
from pptx.dml.color import RGBColor


def rgb(hex_str):
    hex_str = hex_str.lstrip('#')
    return RGBColor(int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16))


TEMPLATES = {
    'corporate_blue': {
        'name': 'Corporate Blue',
        'description': 'Classic professional blue — trusted by Fortune 500 companies',
        'category': 'Business',
        'primary': '#1565C0',
        'secondary': '#42A5F5',
        'accent': '#FFC107',
        'background': '#FFFFFF',
        'title_color': '#1565C0',
        'text_color': '#212121',
        'subtitle_color': '#546E7A',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🔵',
    },
    'dark_executive': {
        'name': 'Dark Executive',
        'description': 'Sleek dark theme with gold accents — executive boardroom ready',
        'category': 'Executive',
        'primary': '#212121',
        'secondary': '#424242',
        'accent': '#FFD700',
        'background': '#1A1A1A',
        'title_color': '#FFD700',
        'text_color': '#F5F5F5',
        'subtitle_color': '#BDBDBD',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '⚫',
    },
    'nature_fresh': {
        'name': 'Nature Fresh',
        'description': 'Organic green palette — perfect for sustainability and wellness',
        'category': 'Sustainability',
        'primary': '#2E7D32',
        'secondary': '#66BB6A',
        'accent': '#FF8F00',
        'background': '#F9FBE7',
        'title_color': '#1B5E20',
        'text_color': '#1B5E20',
        'subtitle_color': '#388E3C',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🟢',
    },
    'creative_orange': {
        'name': 'Creative Orange',
        'description': 'Vibrant startup energy — great for pitches and product launches',
        'category': 'Startup',
        'primary': '#E65100',
        'secondary': '#FF9800',
        'accent': '#1565C0',
        'background': '#FFF8F5',
        'title_color': '#BF360C',
        'text_color': '#3E2723',
        'subtitle_color': '#6D4C41',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🟠',
    },
    'tech_purple': {
        'name': 'Tech Purple',
        'description': 'Modern tech aesthetic with cyan accents — for SaaS and AI pitches',
        'category': 'Technology',
        'primary': '#4A148C',
        'secondary': '#7B1FA2',
        'accent': '#00BCD4',
        'background': '#F3E5F5',
        'title_color': '#4A148C',
        'text_color': '#212121',
        'subtitle_color': '#7B1FA2',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🟣',
    },
    'minimal_white': {
        'name': 'Minimal White',
        'description': 'Apple-inspired minimalism — clean, elegant, distraction-free',
        'category': 'Design',
        'primary': '#212121',
        'secondary': '#757575',
        'accent': '#1565C0',
        'background': '#FFFFFF',
        'title_color': '#212121',
        'text_color': '#424242',
        'subtitle_color': '#757575',
        'title_font_size': Pt(38),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '⚪',
    },
    'ocean_teal': {
        'name': 'Ocean Teal',
        'description': 'Calming blue-green — ideal for healthcare, research, and education',
        'category': 'Healthcare',
        'primary': '#00695C',
        'secondary': '#26A69A',
        'accent': '#FF7043',
        'background': '#E0F2F1',
        'title_color': '#004D40',
        'text_color': '#212121',
        'subtitle_color': '#00695C',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🔵',
    },
    'sunset_warm': {
        'name': 'Sunset Warm',
        'description': 'Warm coral gradient — compelling for marketing and storytelling',
        'category': 'Marketing',
        'primary': '#BF360C',
        'secondary': '#FF7043',
        'accent': '#FDD835',
        'background': '#FFF3E0',
        'title_color': '#BF360C',
        'text_color': '#3E2723',
        'subtitle_color': '#6D4C41',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🔴',
    },
    'bold_red': {
        'name': 'Bold Red',
        'description': 'High-impact power red — for sales, persuasion, and calls to action',
        'category': 'Sales',
        'primary': '#B71C1C',
        'secondary': '#E53935',
        'accent': '#212121',
        'background': '#FFEBEE',
        'title_color': '#B71C1C',
        'text_color': '#212121',
        'subtitle_color': '#C62828',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🔴',
    },
    'navy_pro': {
        'name': 'Navy Professional',
        'description': 'Deep navy authority — for finance, consulting, and legal decks',
        'category': 'Finance',
        'primary': '#1A237E',
        'secondary': '#3949AB',
        'accent': '#FFC400',
        'background': '#E8EAF6',
        'title_color': '#1A237E',
        'text_color': '#212121',
        'subtitle_color': '#3949AB',
        'title_font_size': Pt(36),
        'content_font_size': Pt(18),
        'bullet_font_size': Pt(16),
        'font_name': 'Calibri',
        'icon': '🔷',
    },
}


def get_template(template_id):
    return TEMPLATES.get(template_id, TEMPLATES['corporate_blue'])


def get_all_templates():
    return [{'id': k, **v} for k, v in TEMPLATES.items()]
